/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * QANTUM PRIME - PROPOSAL FACTORY
 * Generates personalized sales proposals for each enriched lead
 * ═══════════════════════════════════════════════════════════════════════════════
 */

const fs = require('fs');
const path = require('path');

const ENRICHED_FILE = path.join(__dirname, '..', '..', 'data', 'real-leads', 'enriched-leads.json');
const PROPOSALS_DIR = path.join(__dirname, '..', '..', 'data', 'proposals');

// Ensure directory exists
if (!fs.existsSync(PROPOSALS_DIR)) {
    fs.mkdirSync(PROPOSALS_DIR, { recursive: true });
}

const TEMPLATES = {
    // For GitHub users without E2E testing
    no_e2e: {
        subject: "🚀 {name} - Your {repo} needs bulletproof E2E testing",
        body: `Hi {name},

I noticed your project **{repo}** ({repo_url}) is built with {language} but doesn't seem to have end-to-end testing coverage.

As projects scale, bugs slip through unit tests. E2E testing catches what unit tests miss.

**QAntum Prime** can help:
- 🛡️ **Ghost Protocol** - Stealth browser automation that bypasses anti-bot detection
- 🔮 **Oracle Analytics** - AI predicts which tests will fail before you run them
- ⚡ **0.08ms Failover** - Self-healing tests that recover from flaky failures

**Special Offer**: Free 14-day trial + setup assistance for open source maintainers.

Want me to show you how QAntum would work with {repo}?

Best,
QAntum Prime AI
https://papica777-eng.github.io/QAntumPage/

P.S. This email was generated by QAntum's own AI - proof that we practice what we preach! 🤖`
    },

    // For Playwright/Cypress users
    testing_upgrade: {
        subject: "⚡ Make {repo}'s Playwright tests 100x faster",
        body: `Hi {name},

I saw you're using Playwright in **{repo}** - great choice! 

But are your tests:
- ❌ Slow in CI/CD pipelines?
- ❌ Flaky with random failures?
- ❌ Blocked by anti-bot detection on some sites?

**QAntum Prime** solves all three:

1. **Parallel Swarm Execution** - Run 100 tests simultaneously across 5 regions
2. **Self-Healing Selectors** - AI automatically fixes broken selectors
3. **Ghost Protocol v2** - Stealth mode that makes Playwright undetectable

Here's a real example:
\`\`\`
Before QAntum: 45 minutes for 200 tests
After QAntum: 27 seconds (100x faster)
\`\`\`

**Free Demo**: I can set up QAntum on your repo in 15 minutes. Interested?

Best,
QAntum Prime
https://papica777-eng.github.io/QAntumPage/`
    },

    // For companies hiring QA
    hiring_replacement: {
        subject: "🤖 {company} - AI QA Engineer that works 24/7 (re: {position})",
        body: `Hi {company} Team,

I saw you're hiring for **{position}**.

What if instead of a human hire, you could have an AI QA engineer that:
- ✅ Works 24/7/365 without breaks
- ✅ Runs 10,000 tests in 30 seconds
- ✅ Never calls in sick
- ✅ Costs less than one month's salary (one-time)

**QAntum Prime** is that engineer.

**Real Numbers**:
- 715,861 lines of battle-tested code
- 0.08ms average failover time
- 5 global regions for distributed testing
- Used by teams processing millions of tests

**ROI Calculator**:
- Average QA salary: $80,000/year
- QAntum Enterprise: $2,997 one-time
- **Savings**: $77,003 in Year 1 alone

Want a live demo? I'll show you QAntum running against your production site.

Best,
QAntum Prime Sales AI
https://papica777-eng.github.io/QAntumPage/pricing.html

P.S. Yes, this outreach was automated by QAntum. We automate everything. 🚀`
    },

    // Generic for organizations
    organization: {
        subject: "🏢 {name} - Enterprise QA automation for your team",
        body: `Hi {name} Team,

I've been following your work on GitHub and I'm impressed by **{repo}**.

For organizations like yours, QAntum Prime offers:

**Enterprise Features**:
- 🌐 Global Swarm (5 regions, infinite parallelization)
- 🔐 SOC2-ready security and audit logs
- 📊 Real-time dashboards and Slack/Discord alerts
- 🤝 Dedicated support and custom integrations

**Case Study**: A similar {language} project reduced their test time from 2 hours to 45 seconds after implementing QAntum.

Would you be open to a 15-minute call to discuss how QAntum could help {name}?

Best regards,
QAntum Prime Enterprise Sales
https://papica777-eng.github.io/QAntumPage/`
    }
};

class ProposalFactory {
    constructor() {
        this.enrichedLeads = [];
        this.proposals = [];
    }

    loadEnrichedLeads() {
        if (fs.existsSync(ENRICHED_FILE)) {
            this.enrichedLeads = JSON.parse(fs.readFileSync(ENRICHED_FILE, 'utf-8'));
            console.log(`📂 Loaded ${this.enrichedLeads.length} enriched leads`);
        } else {
            console.log('❌ No enriched leads found. Run lead-enricher.js first.');
            process.exit(1);
        }
    }

    selectTemplate(lead) {
        // RemoteOK leads - they're hiring
        if (lead.source === 'RemoteOK') {
            return 'hiring_replacement';
        }

        // Check for specific problems
        if (lead.analysis?.problems?.find(p => p.type === 'no_e2e')) {
            return 'no_e2e';
        }

        // Playwright/Cypress users
        if (lead.analysis?.opportunities?.find(o => 
            o.type === 'playwright_user' || o.type === 'cypress_user'
        )) {
            return 'testing_upgrade';
        }

        // Organizations get enterprise pitch
        if (lead.type === 'Organization') {
            return 'organization';
        }

        // Default
        return 'no_e2e';
    }

    fillTemplate(template, lead) {
        let subject = template.subject;
        let body = template.body;

        const replacements = {
            '{name}': lead.name || lead.company || 'there',
            '{company}': lead.company || lead.name || 'Your Company',
            '{repo}': lead.repo_name?.split('/')[1] || lead.repo_name || 'your project',
            '{repo_url}': lead.repo_url || lead.profile_url || '',
            '{language}': lead.language || 'modern technologies',
            '{position}': lead.position || 'QA Engineer',
            '{stars}': (lead.stars || 0).toString()
        };

        for (const [key, value] of Object.entries(replacements)) {
            subject = subject.replace(new RegExp(key, 'g'), value);
            body = body.replace(new RegExp(key, 'g'), value);
        }

        return { subject, body };
    }

    generateProposal(lead) {
        const templateKey = this.selectTemplate(lead);
        const template = TEMPLATES[templateKey];
        const { subject, body } = this.fillTemplate(template, lead);

        // Try to find email
        let email = null;
        if (lead.email) {
            email = lead.email;
        } else if (lead.source === 'GitHub' && lead.name) {
            // GitHub users might have public email - we'd need to fetch profile
            email = `${lead.name}@github.placeholder`; // Placeholder - needs enrichment
        }

        return {
            lead_id: lead.id,
            lead_name: lead.name || lead.company,
            lead_source: lead.source,
            priority_score: lead.analysis?.priority_score || 50,
            template_used: templateKey,
            email: email,
            subject: subject,
            body: body,
            generated_at: new Date().toISOString(),
            status: 'pending',
            // For tracking
            tracking_pixel: `https://papica777-eng.github.io/QAntumPage/track?lid=${lead.id}`,
            cta_link: 'https://papica777-eng.github.io/QAntumPage/pricing.html'
        };
    }

    generateAll() {
        console.log(`
╔═══════════════════════════════════════════════════════════════════════╗
║   📝 QANTUM PRIME - PROPOSAL FACTORY                                  ║
║   Generating personalized sales proposals...                          ║
╚═══════════════════════════════════════════════════════════════════════╝
`);

        this.loadEnrichedLeads();

        for (const lead of this.enrichedLeads) {
            console.log(`\n📧 Generating proposal for: ${lead.name || lead.company}`);
            const proposal = this.generateProposal(lead);
            this.proposals.push(proposal);
            
            // Save individual proposal
            const filename = `proposal-${lead.id}.json`;
            fs.writeFileSync(
                path.join(PROPOSALS_DIR, filename),
                JSON.stringify(proposal, null, 2)
            );
            console.log(`   ✅ Template: ${proposal.template_used}, Priority: ${proposal.priority_score}`);
        }

        // Save all proposals summary
        const summary = {
            generated_at: new Date().toISOString(),
            total_proposals: this.proposals.length,
            by_template: {},
            by_priority: {
                hot: this.proposals.filter(p => p.priority_score >= 90).length,
                warm: this.proposals.filter(p => p.priority_score >= 70 && p.priority_score < 90).length,
                cold: this.proposals.filter(p => p.priority_score < 70).length
            },
            proposals: this.proposals
        };

        // Count by template
        for (const p of this.proposals) {
            summary.by_template[p.template_used] = (summary.by_template[p.template_used] || 0) + 1;
        }

        fs.writeFileSync(
            path.join(PROPOSALS_DIR, 'proposals-summary.json'),
            JSON.stringify(summary, null, 2)
        );

        console.log(`
╔═══════════════════════════════════════════════════════════════════════╗
║   ✅ PROPOSALS GENERATED                                               ║
╠═══════════════════════════════════════════════════════════════════════╣
║   Total: ${summary.total_proposals.toString().padEnd(54)}║
║   🔥 Hot (90+): ${summary.by_priority.hot.toString().padEnd(49)}║
║   🌡️ Warm (70-89): ${summary.by_priority.warm.toString().padEnd(46)}║
║   ❄️ Cold (<70): ${summary.by_priority.cold.toString().padEnd(48)}║
╠═══════════════════════════════════════════════════════════════════════╣
║   Saved to: data/proposals/                                           ║
╚═══════════════════════════════════════════════════════════════════════╝
`);

        return this.proposals;
    }

    // Preview a proposal
    previewProposal(leadId) {
        const proposal = this.proposals.find(p => p.lead_id === leadId);
        if (!proposal) {
            console.log('Proposal not found');
            return;
        }

        console.log(`
═══════════════════════════════════════════════════════════════════════
TO: ${proposal.email || '[EMAIL NEEDED]'}
SUBJECT: ${proposal.subject}
═══════════════════════════════════════════════════════════════════════

${proposal.body}

═══════════════════════════════════════════════════════════════════════
Priority: ${proposal.priority_score} | Template: ${proposal.template_used}
═══════════════════════════════════════════════════════════════════════
`);
    }
}

// Run if called directly
if (require.main === module) {
    const factory = new ProposalFactory();
    factory.generateAll();
    
    // Preview the hottest lead
    if (factory.proposals.length > 0) {
        console.log('\n📧 PREVIEW OF HOTTEST PROPOSAL:\n');
        factory.previewProposal(factory.proposals[0].lead_id);
    }
}

module.exports = { ProposalFactory };
