/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * QAntum v26.0 "Sovereign Nexus"
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * @copyright 2025 Димитър Продромов (Dimitar Prodromov). All Rights Reserved.
 * @license PROPRIETARY AND CONFIDENTIAL
 *
 * This file is part of QAntum.
 * Unauthorized copying, modification, distribution, or use of this file,
 * via any medium, is strictly prohibited without express written permission.
 *
 * For licensing inquiries: dimitar.prodromov@QAntum.dev
 * ═══════════════════════════════════════════════════════════════════════════════
 */
import { EventEmitter } from 'node:events';
/**
 * Agent role identifiers
 */
export type AgentRole = 'shield' | 'sword' | 'surgeon' | 'oracle';
/**
 * Vulnerability severity levels
 */
export type VulnerabilitySeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';
/**
 * Vulnerability types detected by CyberCody (Sword)
 */
export type VulnerabilityType = 'sqli' | 'xss' | 'bola' | 'csrf' | 'ssrf' | 'rce' | 'idor' | 'auth_bypass' | 'info_leak' | 'config_error';
/**
 * Detected vulnerability from CyberCody
 */
export interface DetectedVulnerability {
    /** Unique vulnerability identifier */
    id: string;
    /** Vulnerability type */
    type: VulnerabilityType;
    /** Severity level */
    severity: VulnerabilitySeverity;
    /** Affected endpoint or component */
    target: string;
    /** Proof of concept payload */
    payload: string;
    /** HTTP method used */
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    /** Response indicating vulnerability */
    evidence: string;
    /** CVSS score estimate */
    cvssScore: number;
    /** Detection timestamp */
    detectedAt: Date;
    /** CWE reference if known */
    cweId?: string;
}
/**
 * Regression test generated by Shield
 */
export interface RegressionTest {
    /** Unique test identifier */
    id: string;
    /** Associated vulnerability ID */
    vulnerabilityId: string;
    /** Test name */
    name: string;
    /** Test code (TypeScript/Playwright) */
    code: string;
    /** Expected behavior after fix */
    expectedBehavior: string;
    /** Test assertions */
    assertions: string[];
    /** Generated timestamp */
    generatedAt: Date;
}
/**
 * Security patch generated by Surgeon
 */
export interface SecurityPatch {
    /** Unique patch identifier */
    id: string;
    /** Associated vulnerability ID */
    vulnerabilityId: string;
    /** Affected file path */
    filePath: string;
    /** Original code snippet */
    originalCode: string;
    /** Patched code snippet */
    patchedCode: string;
    /** Patch description */
    description: string;
    /** Validation status */
    validated: boolean;
    /** Generated timestamp */
    generatedAt: Date;
}
/**
 * Feedback loop cycle result
 */
export interface FeedbackCycleResult {
    /** Cycle identifier */
    cycleId: string;
    /** Original vulnerability */
    vulnerability: DetectedVulnerability;
    /** Generated regression test */
    regressionTest: RegressionTest;
    /** Generated security patch */
    securityPatch: SecurityPatch;
    /** Patch validation result */
    patchValidated: boolean;
    /** Total cycle duration in ms */
    duration: number;
    /** Timestamp */
    completedAt: Date;
}
/**
 * Nexus Coordinator configuration
 */
export interface NexusCoordinatorConfig {
    /** Enable verbose logging */
    verbose?: boolean;
    /** Maximum concurrent feedback loops */
    maxConcurrentCycles?: number;
    /** Timeout for patch generation in ms */
    patchTimeout?: number;
    /** Enable automatic patch validation */
    autoValidate?: boolean;
    /** Minimum severity to trigger feedback loop */
    minSeverityForLoop?: VulnerabilitySeverity;
    /** Custom AI model for code generation */
    aiModel?: 'cloud' | 'local';
}
/**
 * Nexus message for inter-agent communication
 */
export interface NexusMessage {
    /** Message ID */
    id: string;
    /** Source agent */
    from: AgentRole;
    /** Target agent */
    to: AgentRole;
    /** Message type */
    type: 'vulnerability' | 'test' | 'patch' | 'validation' | 'status';
    /** Message payload */
    payload: unknown;
    /** Priority level */
    priority: 'critical' | 'high' | 'normal' | 'low';
    /** Timestamp */
    timestamp: Date;
}
/**
 * Nexus Coordinator statistics
 */
export interface NexusStats {
    /** Total vulnerabilities processed */
    vulnerabilitiesProcessed: number;
    /** Total regression tests generated */
    testsGenerated: number;
    /** Total patches generated */
    patchesGenerated: number;
    /** Successful patch validations */
    validatedPatches: number;
    /** Active feedback cycles */
    activeCycles: number;
    /** Average cycle duration in ms */
    avgCycleDuration: number;
    /** Uptime in ms */
    uptime: number;
}
/**
 * NexusCoordinator - The Inter-Agent Intelligence Hub
 *
 * Coordinates the autonomous feedback loop between:
 * - QANTUM (Shield): Generates regression tests for vulnerabilities
 * - CyberCody (Sword): Detects security vulnerabilities
 * - Surgeon: Generates and validates security patches
 * - Oracle: Provides AI-powered analysis and recommendations
 *
 * When CyberCody detects a vulnerability (SQLi, BOLA, etc.), the Nexus:
 * 1. Triggers Shield to generate a regression test
 * 2. Triggers Surgeon to generate a security patch
 * 3. Validates the patch using the regression test
 * 4. Reports the complete cycle result
 *
 * @example
 * ```typescript
 * const nexus = new NexusCoordinator({ verbose: true });
 * await nexus.start();
 *
 * // When CyberCody detects a vulnerability
 * const result = await nexus.processFeedbackLoop(vulnerability);
 * console.log(`Patch validated: ${result.patchValidated}`);
 * ```
 */
export declare class NexusCoordinator extends EventEmitter {
    private config;
    private isRunning;
    private startTime;
    private messageQueue;
    private activeCycles;
    private stats;
    private cycleDurations;
    constructor(config?: NexusCoordinatorConfig);
    /**
     * Start the Nexus Coordinator
     */
    start(): Promise<void>;
    /**
     * Stop the Nexus Coordinator
     */
    stop(): Promise<void>;
    /**
     * Process a complete feedback loop for a detected vulnerability
     *
     * Flow:
     * 1. CyberCody detects vulnerability → Nexus receives
     * 2. Nexus triggers Shield → Generate regression test
     * 3. Nexus triggers Surgeon → Generate security patch
     * 4. Nexus validates patch using regression test
     * 5. Return complete cycle result
     */
    processFeedbackLoop(vulnerability: DetectedVulnerability): Promise<FeedbackCycleResult>;
    /**
     * Generate a regression test for a vulnerability
     */
    private generateRegressionTest;
    /**
     * Generate test code for a specific vulnerability type
     */
    private generateTestCode;
    private getNavigationCode;
    private getAttackCode;
    private getAssertionCode;
    private generateAssertions;
    private getExpectedBehavior;
    /**
     * Generate a security patch for a vulnerability
     */
    private generateSecurityPatch;
    private generatePatchCode;
    private inferFilePath;
    private generatePatchDescription;
    /**
     * Validate a security patch using the regression test
     */
    private validatePatch;
    private calculateValidationScore;
    /**
     * Send a message to an agent
     */
    private sendMessage;
    /**
     * Receive a message from an agent
     */
    receiveMessage(message: NexusMessage): void;
    private handleVulnerabilityMessage;
    private handleTestMessage;
    private handlePatchMessage;
    private handleValidationMessage;
    private handleStatusMessage;
    /**
     * Get Nexus Coordinator statistics
     */
    getStats(): NexusStats;
    /**
     * Check if coordinator is running
     */
    isActive(): boolean;
    /**
     * Get pending messages count
     */
    getPendingMessages(): number;
    /**
     * Get active cycles count
     */
    getActiveCyclesCount(): number;
    /**
     * Get completed cycle by ID
     */
    getCycle(cycleId: string): FeedbackCycleResult | undefined;
    private generateCycleId;
    private generateMessageId;
    private meetsSeverityThreshold;
    private getPriorityFromSeverity;
    private updateAvgDuration;
    private createSkippedResult;
    private log;
}
export default NexusCoordinator;
//# sourceMappingURL=nexus-coordinator.d.ts.map